[project]
org-name = "ShouOUT"
version = "0.0.1"
authors = [""]
keywords = ["shoutout", "endpoint", "API"]
repository = "https://github.com/randimaS/ballerina-package-shoutout"
license = "Apache-2.0"

